sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version

script:
  - bash test.sh
  
  - bash 0x04/image.sh 0x04/images -h
  - bash 0x04/image.sh 0x04/images -c 50
  - bash 0x04/image.sh 0x04/images -p XXX -s YYY
  - bash 0x04/image.sh 0x04/images -w cookie
  - bash 0x04/worldcup.sh 0x04/worldcupplayerinfo.tsv
  - bash 0x04/weblog.sh 0x04/web_log.tsv -h
  - bash 0x04/weblog.sh 0x04/web_log.tsv -H
  - bash 0x04/weblog.sh 0x04/web_log.tsv -i
  - bash 0x04/weblog.sh 0x04/web_log.tsv -u
  - bash 0x04/weblog.sh 0x04/web_log.tsv -x
  - bash 0x04/weblog.sh 0x04/web_log.tsv -r
  - bash 0x04/weblog.sh 0x04/web_log.tsv -U /pub/winvn/readme.txt


after_script:
  - /usr/bin/shellcheck test.sh
  - /usr/bin/shellcheck *.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
